
package valtech.jaxws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.9
 * Tue Oct 18 14:42:52 IST 2022
 * Generated source version: 2.7.9
 */

@XmlRootElement(name = "hi", namespace = "http://jaxws.valtech/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hi", namespace = "http://jaxws.valtech/")

public class Hi {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

